# Generated by Django 3.2 on 2022-05-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azul', '0002_alter_case_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='ransomware',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('WannaCry', 'WannaCry'), ('Locky', 'Locky'), ('Bad Rabbit', 'Bad Rabbit'), ('Ryuk', 'Ryuk'), ('Shade/Troldesh', 'Shade/Troldesh'), ('Jigsaw', 'Jigsaw'), ('CryptoLocker', 'CryptoLocker'), ('Petya', 'Petya'), ('GandCrab 5.2', 'GandCrab 5.2'), ('GoldenEye', 'GoldenEye')], max_length=20),
        ),
    ]
