# Generated by Django 3.2 on 2022-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azul', '0004_alter_case_rams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='exte',
            field=models.TextField(blank=True),
        ),
    ]
