# Generated by Django 3.2 on 2022-06-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azul', '0007_auto_20220606_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metho',
            new_name='Metodologia',
        ),
    ]
