# Generated by Django 3.2 on 2022-08-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azul', '0008_rename_metho_metodologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='ransomware',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='case',
            name='nitempresa',
            field=models.IntegerField(max_length=100, verbose_name='Nit Empresa'),
        ),
    ]
