# Generated by Django 3.2 on 2022-09-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azul', '0009_auto_20220815_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question1', models.CharField(blank=True, max_length=100, verbose_name='Pregunta 1')),
                ('question2', models.CharField(blank=True, max_length=500, verbose_name='Pregunta 2')),
                ('question3', models.CharField(blank=True, max_length=500, verbose_name='Pregunta 3')),
                ('question4', models.CharField(blank=True, max_length=500, verbose_name='Pregunta 4')),
                ('question5', models.CharField(blank=True, max_length=500, verbose_name='Pregunta 5')),
                ('question6', models.CharField(blank=True, max_length=500, verbose_name='Pregunta 6')),
                ('question7', models.CharField(blank=True, max_length=500, verbose_name='Pregunta 7')),
                ('question8', models.CharField(blank=True, max_length=500, verbose_name='Pregunta 8')),
            ],
        ),
    ]
